name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: kentaro-m/auto-assign-action@v1.2.5

      - name: Echo
        env:
          USERNAME: ${{ secrest.USERNAMe }}
        run: echo $USERNAME