name: 'Auto Assign'
on:
  pull_request_target:
    types: [labeled]

jobs:
  checkout:
    permissions: write-all
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: kentaro-m/auto-assign-action@v1.2.5

      - name: Echo
        shell: bash
        env:
          USERNAME: ${{ secrets.USERNAME }}
        run: echo "$USERNAME"