name: 'Auto Assign'
on:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: kentaro-m/auto-assign-action@v1.2.5

      - name: Echo
        shell: bash
        env:
          USERNAME: ${{ secrets.USERNAME }}
        run: echo "$USERNAME"